version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: earthquake-db
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: earthquake-pgdb
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - earthquake-network

networks:
  earthquake-network:
    driver: bridge

volumes:
  postgres-data:
    name: earthquake-postgres-data
